# --- IMPORTANTE AQUÍ ---
# Esta es la dirección donde vivirá mi web
baseURL = 'https://faruthem.github.io/portafolio/'
# ----------------------------------

languageCode = 'es-mx'
title = 'Kevin López Guzmán'

# Habilitar resaltado de sintaxis nativo (Chroma)
[markup]
  [markup.highlight]
    noClasses = true
    guessSyntax = true

[params]
  description = "Ingeniero en Sistemas, Fisioterapeuta & Estudiante de Maestría de administración de las tecnologías"
  bio = "Apasionado por la programación y el mundo Linux."
  # Actualicé esto con usuario de GitHub
  github = "https://github.com/faruthem"
  # Enlace a mi instagram
  instagram = "https://instagram.com/faruthem"

[menus]
  [[menus.main]]
    name = 'Inicio'
    url = '/'
    weight = 10

  [[menus.main]]
    name = 'Go'
    url = '/tags/go/'
    weight = 20

  [[menus.main]]
    name = 'Python'
    url = '/tags/python/'
    weight = 30

  [[menus.main]]
    name = 'Rust'
    url = '/tags/rust/'
    weight = 40  

  [[menus.main]]
   name = 'sobre mi'
   url = '/about/'
   weight = 50

  [outputs]
   home = ["HTML", "RSS", "JSON"]

  [params]
  description = "Portafolio de Kevin López Guzmán. Ingeniero en Sistemas, Fisioterapeuta y Desarrollador."
  author = "Kevin López Guzmán"
  # images = ["/ruta-a-tu-imagen.jpg"] # subir una imagen global y poner su ruta aquí
